@host = http://localhost:5000/api



### Example GET request
GET {{host}}/user HTTP/1.1
content-type: application/json


### Example POST request

### Create An User
POST {{host}}/user HTTP/1.1
content-type: application/json

{
  "name": "Anton",
  "surname": "MOC"
}

### Example PUT request